name: Orderion

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt clean compile
        run: |
          sbt clean compile
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt stage deployHeroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          MONGO_TABLE_COLLECTION: table
          MONGO_RESERVATION_COLLECTION: reservation
          MONGO_RESTAURANT_MAP_COLLECTION: restaurant-map
          LOG_LEVEL: DEBUG
          MONGO_DATABASE: prod_kezek
          HOST: 0.0.0.0,
          SWAGGER_SCHEMES: https
          SWAGGER_HOST: prod-kezek-reservation-core.herokuapp.com
          ENV: prod
        run: |
          sbt -Denv=prod stage deployHeroku